version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami'
    networks:
      - kafka
  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka
  webapp:
    image: gkin/kafka-streaming:latest
    depends_on:
      - zookeeper
      - kafka
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - 'webapp_data:/webapp'
    environment:
      - KAFKA_CLIENT_ADDRESS=localhost:9092
    networks:
      - webnet
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  webapp_data:
    driver: local
networks:
  webnet:
  kafka: